name: modular2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you are publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  google_maps_flutter: ^2.3.0
  location: ^6.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  firebase_storage: ^11.0.7
  cached_network_image: ^3.2.3
  image_picker: ^1.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-Medium.otf
        - asset: fonts/SF-Pro-Display-Heavy.otf
        - asset: fonts/SF-Pro-Display-Bold.otf
    - family: SF-Pro-Text
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
        - asset: fonts/SF-Pro-Text-Semibold.otf
        - asset: fonts/SF-Pro-Text-Medium.otf
        - asset: fonts/SF-Pro-Text-Bold.otf
    - family: SF-Pro-Rounded
      fonts:
        - asset: fonts/SF-Pro-Rounded-Regular.otf
        - asset: fonts/SF-Pro-Rounded-Bold.otf
        - asset: fonts/SF-Pro-Rounded-Medium.otf
        - asset: fonts/SF-Pro-Rounded-Light.otf
        - asset: fonts/SF-Pro-Rounded-Heavy.otf
    - family: LilitaOne
      fonts:
        - asset: fonts/LilitaOne-Regular.ttf
    - family: PoetsenOne
      fonts:
        - asset: fonts/PoetsenOne-Regular.ttf

  assets:
    - assets/images/fondoInicio.png
    - assets/images/fondoInicioSesion.png
    - assets/images/background_perfil.png
